.PHONY: clean All

All:
	@echo "----------Building project:[ xsteem64 - ReleaseDyn ]----------"
	@"$(MAKE)" -f  "xsteem64.mk" && "$(MAKE)" -f  "xsteem64.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ xsteem64 - ReleaseDyn ]----------"
	@"$(MAKE)" -f  "xsteem64.mk" clean
